#!/bin/bash
cd /tmp
tar -zxf pcre-8.45.tar.gz
cd /pcre-8.45
./configure
make
sudo make install

cd /tmp
tar -zxf zlib-1.2.11.tar.gz
cd /tmp/zlib-1.2.11
./configure
make
sudo make install

cd /tmp
tar -zxf openssl-1.1.1g.tar.gz
cd /tmp/openssl-1.1.1g
./Configure linux-x86_64 --prefix=/usr
make
sudo make install

cd /tmp
tar zxf nginx-1.20.2.tar.gz
cd /tmp/nginx-1.20.2

./configure --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --with-pcre=/tmp/pcre-8.45 --with-zlib=/tmp/zlib-1.2.11 --with-http_ssl_module --with-stream --user=nginx --group=nginx
make
sudo make install 

cp -r /tmp/nginx.service /lib/systemd/system/nginx.service
systemctl deamon-reload
systemctl reload nginx.service

cp /tmp/*.html /usr/share/nginx/html/

find /etc/nginx -type d | xargs chmod 750
find /etc/nginx -type f | xargs chmod 640
sed -i "s/daily/weekly/" /etc/logrotate.d/nginx
sed -i "s/rotate 52/rotate 13/" /etc/logrotate.d/nginx
passwd -l nginx
chown -R root:root /etc/nginx
chown root:root /var/run/nginx.pid
chown 644 /var/run/nginx.pid
chmod 400 /etc/nginx/certs/cert.key
